
branches:
  only:
    - master

version: '{branch}-{build}'
image: Visual Studio 2022

configuration: Release

build:
  parallel: true
#  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
  project: PeasyUri.sln

deploy:
  provider: NuGet
  api_key:
    secure: cSVY4kxJ2RhSfG2ARk8KI/c0iacT2pg7bhGsxyBbCZ1qQVYSGg5rsPA+Q4fmQ6GQ
  skip_symbols: true

artifacts:
  - path: '*.nupkg'
